### ISSUE TITLE
TTF version of uushi

### ISSUE THREAD

**Issue by solarnz** [cmvnd/fonts#25]
Hi,

With pango no longer supporting bitmap fonts, is it possible to get a ttf version of uushi? I love using the font but I will need to upgrade pango at some point on my machine.

https://gitlab.gnome.org/GNOME/pango/issues/386

**Comment by cmvnd** [comment]
uushi is abandoned, and I'm not sure if/when a .ttf version is coming. However, there is a .otb version available in the repo.
