### ISSUE TITLE
Berry Bold?

### ISSUE THREAD

**Issue by Barbarossa93** [cmvnd/fonts#31]
I absolutely ADORE spectrum's berry font. Seriously, I have scoured as far as I could across the internet for bitmap fonts and berry is the only one that scratches my itch for the right character shapes and size for my screen. Tewii is nice, but I find it too... curvy for my tastes. Unfortunately, the only thing it lacks for me is a proper bold variant. I'm considering taking a shot at making it myself, but I have no idea where to begin. Do you have any tips?

Otherwise, are you aware of other fonts similar to berry? May have to try those in the mean time.

**Comment by cmvnd** [comment]
Glad you like it. I can probably make and push a bold variant very soon. However, if you want to try your hand at it, both gbdfed and fontforge should have embolden functions. Regardless, I'll mark this as closed once a bold variant is added.

As for similar fonts, you might want to look into Monaco and its variants. Both tewi and berry are derived from Monaco, and uushi drew heavily from those two and the artwiz fonts.

**Comment by Barbarossa93** [comment]
Thank you! Gbdfed was perfect; it's straightforward to use. 

So [here's](https://github.com/Barbarossa93/Forester/blob/main/.fonts/berry-bold.bdf) what I have so far. It's not perfect, but I'm curious to hear your input.

**Comment by cmvnd** [comment]
Personally, I'm not a fan of bold bitmap fonts, but it looks more or less fine. If you're satisfied with it, feel free to submit a pull request.

**Comment by Barbarossa93** [comment]
I think I still need to make a few tweaks, some letters aren't quite right just yet. I'll send a PR as soon as possible
