### ISSUE TITLE
OpenType format

### ISSUE THREAD

**Issue by haarp** [cmvnd/fonts#34]
Hi!

I've been using Lemon on my system for many years now, where space was a constraint and a small readable font was required. Thanks for making it!

Recently, I've noticed instances of Lemon being replaced with boxes. A few hours of research later, it turns out that [Pango 1.44 has dropped support for bitmap fonts](https://blogs.gnome.org/mclasen/2019/05/25/pango-future-directions/). People are naturally [upset](https://gitlab.gnome.org/GNOME/pango/-/issues/386).

There's one saving grace tho: "Note that Harfbuzz does support loading bitmap-only OpenType fonts."

So, would it be a lot of effort to (also) release your fonts in this format? I'm currently refusing to upgrade Pango, but that won't be maintanable forever. I'd rather not lose bitmap fonts.

Cheers!

**Comment by cmvnd** [comment]
Pango-compatible .otb versions of the fonts are already in the repo. Use those instead of the .pcf/.bdf versions.

**Comment by haarp** [comment]
Ah, so that's what "Medium" is. I thought it was some variant and didn't pay it much heed :P

Thanks!
