### ISSUE TITLE
Can you add cpu icons to uushi?

### ISSUE THREAD

**Issue by Ploppz** [cmvnd/fonts#9]
If I am not mistaken, currently the cpu icons, among some few other icons, are only implemented in the lemon font. Could you add the cpu icons (and eventually the other ones that uushi doesn't have) to uushi? This would be great as I am limited to using only one of your lovely fonts (and Lemon has a bit small icons for me).

**Comment by noctuid** [comment]
Yeah, I'd love to see the mail/envelope icon, for example, in uushi.

**Comment by cmvnd** [comment]
uushi is abandoned. However, you can define an icon font (eg, lemon or Siji) as a fallback for uushi.
